[package]
name = "web_brain"
version = "0.1.0"
authors = ["jchaput <piinkyz05@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "*"
serde_derive = "*"
brain-rs = { path = "../" }
