[package]
name = "web_brain"
version = "0.1.0"
authors = ["jchaput <piinkyz05@gmail.com>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.8"
serde = "0.9.15"
serde_derive = "0.9.15"
brain-rs = { path = "../" }
